### ISSUE TITLE
Refresh fails after some time

### ISSUE THREAD

**Issue by lakaila** [azure-storage/deco#355]
(Used Linux version)

Refresh failed after the application has been idle for some time. Maybe there is some kind of session which is not active anymore?

The blob list gets cleared, but the items are not fetched again. Console says:

> [25288:0929/123944:INFO:CONSOLE(10)] ""Error: Index out of range\n    at new Error (native)\n    at Error.r (file:///tmp/.org.chromium.Chromium.8aBd2o/dist/assets/vendor-de0e1509571af5f2eb153895f9c512f6.js:7:2939)\n    at Array.e.default.i.Mixin.create.removeAt (file:///tmp/.org.chromium.Chromium.8aBd2o/dist/assets/vendor-de0e1509571af5f2eb153895f9c512f6.js:11:11139)\n    at T.u.arrayComputed.removedItem (file:///tmp/.org.chromium.Chromium.8aBd2o/dist/assets/vendor-de0e1509571af5f2eb153895f9c512f6.js:10:22320)\n    at Object.m.flushChanges (file:///tmp/.org.chromium.Chromium.8aBd2o/dist/assets/vendor-de0e1509571af5f2eb153895f9c512f6.js:10:15231)\n    at Object.m.itemPropertyDidChange (file:///tmp/.org.chromium.Chromium.8aBd2o/dist/assets/vendor-de0e1509571af5f2eb153895f9c512f6.js:10:14876)\n    at Object.e.observer (file:///tmp/.org.chromium.Chromium.8aBd2o/dist/assets/vendor-de0e1509571af5f2eb153895f9c512f6.js:10:12617)\n    at Object.w [as apply] (file:///tmp/.org.chromium.Chromium.8aBd2o/dist/assets/vendor-de0e1509571af5f2eb153895f9c512f6.js:8:12944)\n    at Object.h [as sendEvent] (file:///tmp/.org.chromium.Chromium.8aBd2o/dist/assets/vendor-de0e1509571af5f2eb153895f9c512f6.js:7:5326)\n    at n.flush (file:///tmp/.org.chromium.Chromium.8aBd2o/dist/assets/vendor-de0e1509571af5f2eb153895f9c512f6.js:7:24881)\n    at Object.p [as endPropertyChanges] (file:///tmp/.org.chromium.Chromium.8aBd2o/dist/assets/vendor-de0e1509571af5f2eb153895f9c512f6.js:7:30717)"", source: file:///tmp/.org.chromium.Chromium.8aBd2o/dist/assets/vendor-de0e1509571af5f2eb153895f9c512f6.js (10)

**Comment by lakaila** [comment]
Hmm actually the refresh operation failed even when done immediately after startup.
